### ISSUE TITLE
HealthCheck triggers continously

### ISSUE THREAD

**Issue by DL5SMB** [doubleSlashde/Busylight-Client#4] opened 2024-02-19 23:10 UTC
So, I finally got it working with teams and manually. 

Thank you, it's a nice "little" project - you put a lot of work in it.

However it turns out, that regularly the light turns off after about 5-10 seconds,
the log showing it als caused due to a health check.

I can turn it on again by toggling between manual and teams mode again, but it will most likely turn off again several seconds later.
Sometimes it works stable and then again: Back to the described error cycle.

Are there any known workarounds / solutions? Is this a connection / time lag problem?
Is it possible to make this check a bit more robust?

```
`23:42:34.003 | EventThread COM8 | DEBUG | d.d.u.u.UsbAdapter | Update to color '0xffa500ff'. |
23:42:34.010 | EventThread COM8 | DEBUG | d.d.u.u.UsbAdapter | Data is available. |
23:42:34.010 | EventThread COM8 | INFO  | d.d.u.u.UsbAdapter | Successfully transmitted image. |

**23:42:39.091 | Health | INFO  | d.d.u.v.ConfigurationView | Turn off automatically at '01:42:33.747380700' |**

23:42:39.515 | UsbAdapterActionQueue Thread | DEBUG | d.d.u.u.UsbAdapter | Start execution of action. |
23:42:39.564 | EventThread COM8 | DEBUG | d.d.u.u.UsbAdapter | Data is available. |
23:42:39.564 | EventThread COM8 | INFO  | d.d.u.u.UsbAdapter | Device is ready for image change. |
23:42:39.564 | EventThread COM8 | DEBUG | d.d.u.u.UsbAdapter | Update to color '0x000000ff'. |'
```

**Comment by Death111** [comment] 2024-02-20 22:12
The first part is great to hear :)

Actually, we were not aware of the issue you described. I'm quite sure that you found a bug which is caused by staying up late ;) We will update you tomorrow.
Thank you for reporting the issue and providing the logs!

@mairKi could you have a look into this?

**Comment by mairKi** [comment] 2024-02-22 12:34
Hey thanks for your Bug :)

according to my analysis, the problem is that the time out goes to a new day and I don't take that into account in my If condition
 I am working on a fix, unfortunately there is currently no way around this. 
 
![image](https://github.com/doubleSlashde/Busylight-Client/assets/106583177/4014882c-251e-42f1-8a0c-151d54367e97)

**Comment by Death111** [comment] 2024-04-15 08:51
Hey @DL5SMB,
we did create a fix and merged it into develop. If you like to confirm you could download the .jar from https://github.com/doubleSlashde/Busylight-Client/actions/runs/8680515730 validate for yourself. Our tests were successfull :)
Thank you for reporting the issue and your patience!

**Comment by DL5SMB** [comment] 2024-04-15 21:30
Hi @Death111 @mairKi 
I just tested it with my setup and I can confirm it works great ;-) Thanks a lot.

**Comment by Death111** [comment] 2024-04-18 13:48
Perfect. Thanks for also validating :) I'll go on and close this issue then.

**Closed as completed by Death111** 2024-04-18 13:48 UTC
Labels: bug
